### ISSUE TITLE
Support for mailto and other URIs

### ISSUE THREAD

**Issue by acostalima** [moxystudio/js-proper-url-join#27]
Should we consider adding support for `mailto` URI and others alike? Or would that be out of scope of this module?

Currently, unlike `http` and `https`, `mailto` appears to somehow be treated like a relative URL as a leading slash is prepended to the output.

**Comment by satazor** [comment]
Great question. This module was designed specifically for URLs and did not take into consideration other type of URIs. I don’t know if it makes sense to support other URIs, e.g. how join would work for mailto?

**Comment by acostalima** [comment]
AFAIK, `mailto` scheme differs from `http` where the following does not exist:

- Double forwarding slashes following the colon that immediately follows the scheme
- Path consisting of segments, each separated by a sigle forwarding slash

Therefore, we would have to ignore joins for `mailto` and other similar URI schemes. Query parameters are supported and the sequence format is exactly the same.

**Comment by acostalima** [comment]
Actually, I think I made a mistake above. It is possible to, as part of the path, specify a sequence of e-mail addresses separated by a comma:

```mailto:foo@foo.com,bar@bar.com?...```

**Comment by acostalima** [comment]
We shall not broaden the scope of this module to include support for URIs.
