### ISSUE TITLE
Add option to keep leading/trailing slashes

### ISSUE THREAD

**Issue by sveneh** [moxystudio/js-proper-url-join#31]
We have a case where we have to build urls programmatically and want to keep the leading and trailing slashes if there are any. 

It would be great to have a third option e.g `trailingSlash : 'keep'` to support this use case.

**Comment by satazor** [comment]
@sveneh Looks reasonable. Could you work on a PR adding that but also for leadingSlash?

**Comment by ubmit** [comment]
I'm working on this issue [here](https://github.com/moxystudio/js-proper-url-join/pull/32). Let me know if you have any suggestion!

**Comment by satazor** [comment]
Fixed by #32
