### ISSUE TITLE
Bump query-string version

### ISSUE THREAD

**Issue by ghettojezuz** [moxystudio/js-proper-url-join#40]
Hi!

Can you bump `query-string` version to the latest please? Current version has transitive dependency `decode-uri-component: "^0.2.0"` that is vulnerable to Improper Input Validation resulting in DoS. The latest version of `query-string` has `decode-uri-component: ^0.2.2` that fixes the problem

**Comment by satazor** [comment]
Hi! Please make a PR and I will merge it and release a new version 🙏

**Comment by satazor** [comment]
Released!

**Comment by ghettojezuz** [comment]
Thank you 🙏🏻

**Comment by ghettojezuz** [comment]
@satazor Hi again! Do you have permission to approve this PR?
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70912
